[package]
name = "rusty-chip"
version = "0.1.0"
authors = ["Cedric Martens <cedricmartens98@gmail.com>", "Adrien Tremblay <adrien@adrientremblay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
